### ISSUE TITLE
Publisher confirms with mandatory=True

### ISSUE THREAD

**Issue by LukeMathWalker** [CleverCloud/lapin#289] opened 2020-06-16 22:00 UTC
## What I am trying to accomplish
Detect when I am publishing a message to an exchange but there is no queue bound to it to receive it.

## How
I enabled publisher confirms on a channel and published a message to a direct exchange enabling persistency (`delivery_mode: 2`) with mandatory set to `true`.

A minimal example looks like this:
```rust
use tokio_amqp::*;
use lapin::{Connection, ConnectionProperties, ExchangeKind, BasicProperties};
use lapin::options::{ConfirmSelectOptions, ExchangeDeclareOptions, BasicPublishOptions};
use lapin::types::FieldTable;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let addr = std::env::var("AMQP_ADDR").unwrap_or_else(|_| "amqp://127.0.0.1:5672/%2f".into());
    let connection = Connection::connect(&addr, ConnectionProperties::default().with_tokio()).await?;
    let exchange = "test";
    let channel = connection.create_channel().await?;
    channel
        .confirm_select(ConfirmSelectOptions { nowait: false })
        .await?;
    channel.exchange_declare(
        exchange,
        ExchangeKind::Direct,
        ExchangeDeclareOptions::default(),
        FieldTable::default(),
    ).await?;
    let options = BasicPublishOptions {
        mandatory: true,
        immediate: false,
    };
    // Delivery mode: Non-persistent (1) or persistent (2).
    let properties = BasicProperties::default().with_delivery_mode(2);
    println!("Publishing...");
    let confirm = channel
        .basic_publish(exchange, "routing", options, vec![], properties)
        .await?
        .await?;
    println!("Confirmation: {:?}", confirm);

    Ok(())
}
```

The program never completes - it prints "Publishing..." but never reaches the second print statement.
The same routine using Python's pika causes an an `UnroutableError' exception, which is what I was expecting to get as an error with `lapin`:
```python
import pika

connection = pika.BlockingConnection()
channel = connection.channel()
channel.confirm_delivery()
channel.exchange_declare("test")
try:
    channel.basic_publish(exchange='test',
                          routing_key='test',
                          body='Hello World!',
                          mandatory=True,
                          properties=pika.BasicProperties(delivery_mode=2))
    print('Message publish was confirmed')
except pika.exceptions.UnroutableError:
    print('Message could not be confirmed')
except Exception as e:
    print(e)
```

Am I doing something obviously wrong or have I hit a bug? :thinking:

**Comment by LukeMathWalker** [comment] 2020-06-16 22:01
Worth saying that `delivery_mode` could actually be stripped from the minimal example: it hangs both with persistent and non-persistent mode.

**Comment by LukeMathWalker** [comment] 2020-06-16 22:37
Digging around I think the issue lies in the way RabbitMQ responds to an unroutable message: it returns 
```
[2020-06-16T22:17:53Z TRACE lapin::channels] will handle frame: Method(1, Basic(Return(Return { reply_code: 312, reply_text: ShortString("NO_ROUTE"), exchange: ShortString(""), routing_key: ShortString("test2") })))
[2020-06-16T22:17:53Z TRACE lapin::channels] will handle frame: Header(1, 60, AMQPContentHeader { class_id: 60, weight: 0, body_size: 4, properties: AMQPProperties { content_type: None, content_encoding: None, headers: None, delivery_mode: None, priority: None, correlation_id: None, reply_to: None, expiration: None, message_id: None, timestamp: None, kind: None, user_id: None, app_id: None, cluster_id: None } })
[2020-06-16T22:17:53Z TRACE lapin::channels] will handle frame: Body(1, [97, 115, 100, 102])
```
which is in the end handled by https://github.com/CleverCloud/lapin/blob/6ee98cc6387688003d77200b33be5a5f6d293a27/src/channel.rs#L928 - should that method deal with the pending publisher confirmation given that an ack/a nack will never arrive (if I understood it correctly)?

**Comment by Keruspe** [comment] 2020-06-17 05:38
Does https://github.com/CleverCloud/lapin/blob/lapin-1.x/examples/publisher_confirms.rs work for you. It’s supposed to be there to test just that

**Comment by Keruspe** [comment] 2020-06-17 05:48
Oh right, I think I see what the problem is

**Comment by LukeMathWalker** [comment] 2020-06-17 06:56
> Does https://github.com/CleverCloud/lapin/blob/lapin-1.x/examples/publisher_confirms.rs work for you. It’s supposed to be there to test just that

It seems to have exactly the same issue - the await on https://github.com/CleverCloud/lapin/blob/6ee98cc6387688003d77200b33be5a5f6d293a27/examples/publisher_confirms.rs#L123 never terminates.

**Comment by LukeMathWalker** [comment] 2020-06-17 07:53
Digging deeper, it seems it hangs on the acquisition of the status lock, here:
https://github.com/CleverCloud/lapin/blob/6ee98cc6387688003d77200b33be5a5f6d293a27/src/channel_status.rs#L31
when called from
https://github.com/CleverCloud/lapin/blob/6ee98cc6387688003d77200b33be5a5f6d293a27/src/channel.rs#L361

**Comment by Keruspe** [comment] 2020-06-17 07:54
It's a regression from f7a125892a5a5b0c7a29f94c8715d4be848ce6c7

**Comment by Keruspe** [comment] 2020-06-17 08:00
Fixed in 1.1.1 for the "normal" case + added a test

Will fix for mandatory later

**Comment by Keruspe** [comment] 2020-06-17 08:01
Hrm, no, actually it should be fixed for mandatory too!

**Closed by Keruspe** 2020-06-17 08:01 UTC

**Comment by LukeMathWalker** [comment] 2020-06-17 09:00
Amazing, thank you!
Would opening a PR with a test to catch this regression be appreciated? (I can't see the fix commit on `master`, so I assume you released from a local branch).

**Comment by Keruspe** [comment] 2020-06-17 09:01
It's in the lapin-1.x branch. I have some local changes in master, will merge later
